theme: jekyll-theme-slate
title: JB's homepage
description: Support by donating ğŸ’• <a href="https://www.paypal.com/paypalme/borbejonry">PayPal</a>. Sent me a message so that I can record your donation ğŸ’• . 


